### ISSUE TITLE
Request for universal example

### ISSUE THREAD

**Issue by geraldyeo** [Widdershin/cycle-restart#25]
First, thanks for creating this. 

I'm new to the Cycle ecosystem, and is finding it hard to piece together a working universal app with hot module replacement. It will be good to have an example of this.

**Comment by SkaterDad** [comment]
One option would be to run 2 servers. 
 1. HMR server that updates the client Javascript bundle. 
 2. The universal server which renders your cycle app.  This server could be launched by Nodemon or something similar, which would restart the server on JS file changes.   I don't think true HMR has much value server side since the requests are short and not keeping your cycle app running. 

Of course you'll need a build process which runs Babel on your universal server files automatically. 

Mixing both of those servers into 1 would be quite interesting, just not sure it's worth it?

**Comment by geraldyeo** [comment]
I used another starter kit of mine with webpack to experiment, seems to work.
https://github.com/geraldyeo/universal-cycle-starter

This Cycle starter kit is still a work in progress.

**Comment by Widdershin** [comment]
Awesome, once you get everything working, let me know and I'll add a link to the readme.
