### ISSUE TITLE
module.hot.accept callback not invoked?

### ISSUE THREAD

**Issue by ronag** [Widdershin/cycle-restart#37]
Following the example but using the following command line:

```bash
budo index.js:bundle.js -d public -- -t babelify -p browserify-hmr
```

"Reloading" is never printed:

```javascript
if (module.hot) {
  module.hot.accept('./src/app', () => {
    console.log('Reloading')
    const app = require('./src/app').default
    restart(app, drivers, { sinks, sources }, isolate)
  })
}
```

However, in the browser log it prints:

```
[HMR] Updated modules ["src/components/hub/browser/asset.js", "src/components/hub/browser/grid.js", "src/components/hub/browser/index.js", "src/components/hub/index.js", "src/app.js"]
```

Any ideas what I might be doing wrong?

**Comment by averyvery** [comment]
Did you ever resolve this issue? Having a similar one.

**Comment by wyqydsyq** [comment]
This seems to be an issue with HMR rather than cycle-restart.

cycle-restart is only concerned with restoring your application state when your `.accept()` callback reruns your Cycle instance (`restart()`).

If the accept callback itself isn't behaving as expected then that's an issue with the HMR client library or how it is being used. `console.log`ging out from the accept callback in the example included with this library logs out fine so I'm unable to reproduce this.

**Comment by Widdershin** [comment]
@averyvery Could you provide the full source code of the file that is calling `module.hot.accept`?

**Comment by averyvery** [comment]
Apologies, I think I actually commented on the wrong issue while a lot of tabs were open. What I was seeing wasn't related to this library at all.
